### ISSUE TITLE
No need for non interactive install script

### ISSUE THREAD

**Issue by lucid-at-dream** [xanderhendriks/docker-stm32cubeide#1]
Hi!

Consider adding the following environment variable to your Dockerfile to bypass the license checks
```
ENV LICENSE_ALREADY_ACCEPTED=1
```

Also, at least for me, I also needed to add the Timezone info:
```
ENV TZ=Etc/UTC
```

Cheers!

**Comment by xanderhendriks** [comment]
Thanks for the tip. I have updated the repo and pushed the 1.8.0 and 1.9.0 releases to [hub.docker.com](https://hub.docker.com/repository/docker/xanderhendriks/stm32cubeide/)
