### ISSUE TITLE
Packages not installable: libncurses5, libpython2.7, libwebkit2gtk-4.0-37 

### ISSUE THREAD

**Issue by atrink** [xanderhendriks/docker-stm32cubeide#11]
Hi!
Unfortunately I get a build error with the latest dockerfile: 

 > [stage-1 4/4] RUN chmod +x /tmp/stm32cubeide-installer.sh &&     /tmp/stm32cubeide-installer.sh &&     rm /tmp/stm32cubeide-installer.sh:
2.018 Creating directory makeself_dir_1PdcaK
2.020 Verifying archive integrity...  100%   All good.
4.262 Uncompressing STM32CubeIDE installer  100%
6.160 Reading package lists...
6.683 Building dependency tree...
6.781 Reading state information...
6.837 Some packages could not be installed. This may mean that you have
6.837 requested an impossible situation or if you are using the unstable
6.837 distribution that some required packages have not yet been created
6.837 or been moved out of Incoming.
6.837 The following information may help to resolve the situation:
6.837
6.837 The following packages have unmet dependencies:
6.899  st-stm32cubeide-1.16.0 : Depends: libncurses5 but it is not installable
6.899                           Depends: libpython2.7 but it is not installable
6.899                           Depends: libwebkit2gtk-4.0-37 but it is not installable
6.900 E: Unable to correct problems, you have held broken packages.

How can I solve this?
Thanks

**Comment by xanderhendriks** [comment]
Do you need to build your own? Otherwise you are better off using the image from [hub.docker.com](https://hub.docker.com/r/xanderhendriks/stm32cubeide)

**Comment by xanderhendriks** [comment]
Closing for lack of response
