### ISSUE TITLE
Option to fail on missing project

### ISSUE THREAD

**Issue by Love-Pengy** [xanderhendriks/docker-stm32cubeide#15]
This is more of a question than an issue, but is there currently a way to have it return an error code instead of success code on misconfigured/missing project? At the moment if the project can't be found it gives a warning message: `WARNING: No Project matched "<project name>". Skipping...` but will succeed on that job. I would like it to fail

**Comment by xanderhendriks** [comment]
I don't quite understand your question. When using the docker you run your own commands, so you can just add an extra command to check if the expected output is there. Or are you using [action-build-stm32cubeide](https://github.com/xanderhendriks/action-build-stm32cubeide), which is in another repository.

**Comment by Love-Pengy** [comment]
My apologies I am using the action, I will close this and resubmit it in the right repository
