### ISSUE TITLE
Bump version to v1.10.1 CubeMx

### ISSUE THREAD

**Issue by maebli** [xanderhendriks/docker-stm32cubeide#2]
Hello

Would it be possible to add the v1.10.1 CubeMx version

Thanks

**Comment by xanderhendriks** [comment]
Sure. Let me download and create the new docker.

**Comment by xanderhendriks** [comment]
Done. Now available on [hub.docker.com](https://hub.docker.com/repository/docker/xanderhendriks/stm32cubeide). The [github action](https://github.com/xanderhendriks/action-build-stm32cubeide) has also been updated.

**Comment by maebli** [comment]
Awesome! Thanks a lot for this
