### ISSUE TITLE
Bump version to v1.14 CubeMx

### ISSUE THREAD

**Issue by Linjieqiang** [xanderhendriks/docker-stm32cubeide#4]

**Comment by xanderhendriks** [comment]
Please use [version 11.0](https://hub.docker.com/r/xanderhendriks/stm32cubeide/tags)

**Comment by xanderhendriks** [comment]
@Linjieqiang is this working for you? Can this issue be closed?

**Comment by xanderhendriks** [comment]
Unfortunately the original requester didn't report back if this is working. No problems have been reported by other people, so closing this issue.
